### ISSUE TITLE
Word Wrapping

### ISSUE THREAD

**Issue by zaphon** [Total-RP/Total-RP-3#1146]
## Describe the issue
When viewing a user's profile and hovering over a piece of information that is longer than visible, it used to word wrap it and was viewable, but something changed and it's now showing all on one line and wider than the screen.

## Expected behaviour
To be wrapped so that it doesn't flow off the screen and is visible.

## Issue checklist

- [X] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Click a user with a TRP profile
2. Open their profile
3. Hover over an item that is truncated in the TRP window.

## Additional files
![WoWScrnShot_100324_114106](https://github.com/user-attachments/assets/c73bb905-228c-4150-9ef7-45675f8f68b4)

**Comment by Solanya** [comment]
Those tooltips are meant to show the full text when the field value gets trimmed due to window size.
They are not however designed to allow people to write paragraphs in fields very clearly not intended for them.

The word wrapping change is probably an unintended consequence of unrelated tooltip changes, but if anything was to be done, we'd be more likely to add a hard cap on the additional information field values to prevent misuse of those fields.
