### ISSUE TITLE
TRP3's toolbar is above the World Map frame

### ISSUE THREAD

**Issue by Ellypse** [Total-RP/Total-RP-3#323]
Total RP 3's toolbar is incorrectly displayed above the world map frame, which is especially bad when the map is in fullscreen.

![WoWScrnShot_070719_222600](https://user-images.githubusercontent.com/9035119/60773475-78cbab00-a106-11e9-8064-4b3418457230.jpg)

**Comment by Meorawr** [comment]
Blizzard don't set the strata of the world map frame to FULLSCREEN, instead they just raise it above the frame level of everything else one time (which is why things like pressing the talent hotkeys shows that panel above the map).

Only real fix is to change the default strata of the toolbar down to MEDIUM. Any higher and it'll overlay the map. This also fixes the *other* issue where the toolbar overlays our own frame when it itself is maximized.
