### ISSUE TITLE
Cross-Realm funtion for the Xtensionxtooltip2 channel would be nice

### ISSUE THREAD

**Issue by TheArchitect01** [Total-RP/Total-RP-3#369]
**Is your feature request related to a problem? Please describe.**
It is frustrating to be on the wrong realm when roleplaying with others from other realms is the activity you want to try out.

**Describe the solution you'd like**
The channel controls the profile detection. Without it I can't read other profiles and they can't read mine.

Fixing this, so we can communicate cross-realm would dramatical increase the amount of People we can roleplay with.
**Describe alternatives you've considered**
Otherwise I would like to know a different Addon, which does do that.

**Additional context**

**Comment by Ellypse** [comment]
Cross-realm functionnality is restricted by Blizzard and it is not something we can add ourselves.

RP add-ons use [addon messages](https://wowwiki.fandom.com/wiki/API_SendAddonMessage) via whispers, not the xtensionxtooltip2 channel, for transfering profile data. Because we cannot know for sure if people are from a server connected to yours (as in the same auction house, major city channels, etc.) or not, we are actually sending requests to everyone, including people from other servers, but because of Blizzard's limitation those requests silently fail server side. As such, if Blizzard was to ever allow sending add-on data via whispers to players from other servers, the add-on will suddenly work cross server without even needing an update on our end.

The xtensionxtooltip2 channel is only used to broadcast server wide requests such as requesting for people's location on the map or sending local sounds in Extended.

In the meantime, we have added support for cross server between group/raid members and between Battle.net friends, because there exist ways for add-ons to communicate cross server in those situations.

**Comment by TrinitysEnd** [comment]
Just to tag onto this, you can use the Addon Cross RP to pseudo connect cross realm profiles together by doing this complicated bouncing of B.NET whispers across. So basically, your profile is sent to someone who has a b.net friend with someone who is on that server and online. They receive it and send it to the person trying to connect to you. It only works if there is a connection there somewhere, so it sometimes just won't work. This is a very backdoor way to get around this, but it is theoretically the best bet, and of course, all parties need to have the Cross RP addon. It can also be used to communicate between factions. Again, not perfect, and requires a brute force method that is not fully supported by Blizzard.
