### ISSUE TITLE
"Neutral" Status option

### ISSUE THREAD

**Issue by Corij234** [Total-RP/Total-RP-3#418]
Hi there!

Right now, I'm using the German version of the addon and I'm missing a neutral "default" option regarding character status and roleplaying experience - I mean the option to NOT choose either of the options to show. 

I have no idea what other roleplaying servers look like, but on mine, people using the addon will be flagged as "experienced roleplayers" that are "ooc" 90% of the time, because there is no neutral option...

IMHO this discourages an immersive world rather than help it (which is probably the intention of the addon):

1) People are marked as out of character most of the time, because they haven't actively started rp or were actively looking for it at the moment - there's just no "middle ground" in between the two
Consequences are:
->ooc taggers are "officially not there" and think they are entitled to behave in a way to disturb immersion, because they are ooc and can jump around on other people with their fiery demon horses if they want to (opinion stated in the server forum regarding this, unfortunately lived by by way too many people in the cities on our server, even using ooc in the /s channel - just because they are tagged ooc and not ic)
-> at the very least, even if they do not disturb other people's immersion, that way they appear not willing to be rp'd at -> discouraging people to rp with them more than if there was no flag at all 
I really feel a neutral option that leaves it open if the character is ooc or ic would benefit spontaneous roleplay in the cities and make them more "lived in" (as they were in Vanilla in the beginning)

2) You only ever see "experienced" roleplayers because everyone's who's played more than a day marks themselves as experienced, even if they still mix ooc/ic and use player knowledge in rp (there's just no option for simply "roleplayer", i.e. "not a beginner, but still too insecure to call themselves experienced and pretend they know everything or make no mistakes") 
-> It's way harder to talk to someone who considers themselves experienced about using the avatar information in rp (like level as age etc) than with with someone who knows they are somewhere in between a beginner and someone who has years of experience and just doesn't do that sort of thing.

Other flag addons have these "neutral" options, but TRP3 is the one predominantly used by nearly everyone, so it would be nice to have these options here, too.

**Comment by Solanya** [comment]
Hi. Not sure we follow you on both points.

1 - Players are either willing to roleplay their character at the moment, or they aren't. It's unclear what a 3rd "middle" option would communicate, it just sounds confusing to "leave open" whether the character should be interacted with or not. Either they should be, in which case they can flag themselves as IC, or they shouldn't and they should be OOC. If 90% are OOC, that is their choice.

> Consequences are:
->ooc taggers are "officially not there" and think they are entitled to behave in a way to disturb immersion, because they are ooc and can jump around on other people with their fiery demon horses if they want to

Actively disrupting roleplay is a reportable offense and Blizzard has punished repeating offenders in the past. That said, a mere OOC flag is not the reason they disrupt, nor would they care if it was changed in any way.

> -> at the very least, even if they do not disturb other people's immersion, that way they appear not willing to be rp'd at -> discouraging people to rp with them more than if there was no flag at all

If they are not willing to do RP, why should we force them? It is their choice at the moment.

2 - Regarding roleplay experience, while the naming convention could be discussed, "Experienced roleplayed" is the default. It doesn't show anything in the tooltip or the profile, and a lot of times people don't pay attention to the dropdown anyway. While there could be a better emphasis on the dropdown in the future, the options themselves are unlikely to change, and again if someone doesn't want to set themselves as willing to be advised on how to roleplay, it is their choice.

> Other flag addons have these "neutral" options

I'm not sure what addon you are referring to, because neither MyRolePlay nor XRP does. For both of them, the additional options are different wordings for "in character" (if the player is looking for RP or managing an event), and how much time they spend IC vs OOC on average (with only a beginner option).

**Comment by Corij234** [comment]
> it just sounds confusing to "leave open" whether the character should be interacted with or not

That is just the "default" state of any roleplayer who doesn't use a flag at all. (Which some role players also do, because they don't want to be forced to decide on a firm status all the time while playing, not being open to spontaneous interactions). People may be "ooc" looking through mail but still happy to have rp... but just didn't switch the status because no one rechecks every minute "Would I like rp now?" and change it accordingly. I don't see that as forcing anyone... As ist was before flags were widely used: people on a rp server are open to rp, even if they are not actively seeking it at the moment, no need to check a status every 5 minutes or run around ooc by default because you did one thing that was strictly ooc once within the hour.

> Actively disrupting roleplay is a reportable offense and Blizzard has punished repeating offenders in the past. That said, a mere OOC flag is not the reason they disrupt, nor would they care if it was changed in any way.

No, Blizzard doesn't do anything on our classic server regarding breaking rp rules like using the /s to write things like "I'm gonna pvp til server reset lol" or jumping around on demon horses on conversations. Maybe they would if it went on for a very long time so it was very ovious griefing. But now, they don't.

And regarding the behaviour: If someone sees 99% people flagged ooc around them, it does give them the "So who cares about immersion if everyone's ooc all the time"-opinion, as people stated in the server forum. Yes, it's their choice, but it does affect others and people being people, the neutral option not to have to choose a status might help. 

> if someone doesn't want to set themselves as willing to be advised on how to roleplay, it is their choice.

Sure it is. But there are roleplayers in between complete beginners and experienced roleplayers. And they can't flag themselves as such as of now. Or turn off the distinction because they don't fit in.


> I'm not sure what addon you are referring to, because neither MyRolePlay nor XRP does.

The old flag rsp had and GnomTecBadge has the option to just not choose a status, so running around on a rp server being open to rp generally, without having to change status for every action (which people just don't do, even if they might enjoy rp after doing something strictly ooc).
Unfortunately most people use TRP3 though because they want more than just the flag to show a short character description the engine doesn't allow for (which I also thought was the main reason flag rsp existed in Vanilla).

> Not sure we follow you on both points.

Of course, I get you have reasons to give out the addon the way you did. 
I just tried it out because everyone else uses it and thought I'd try to comment to be able to keep using it as everyone else does.
Those are just points that would really help me, maybe others as well, who also just use this addon, because the less known ones aren't widely used.

**Comment by Solanya** [comment]
The default status in TRP3 if you don't touch anything is IC. You have to manually set yourself OOC. Players set their status knowingly to indicate that at present they are willing to RP. Of course if they have to take an OOC action they can just do so and nobody follows their every move to make sure that everything is 100% in character, the flag is just a general indication that they are open to RP. Saying that everyone or even a majority wants to roleplay even if they are set OOC is just wrong.

If most players don't want to roleplay despite having a RP addon, it is unfortunate, but we are not the RP police, we only provide tools to help people who want to do so. As for how Blizzard handles reports, I am aware of multiple times where they have intervened when people were actively disrupting, but other than that I cannot speak for them on their policies.

Again, regarding experienced, I am open to discuss changing the wording of the default option, we considered but didn't find an appropriate alternative so far, but we don't want to add granularity to it. If you want to learn roleplay, set beginner. If you want to teach roleplay, set volunteer. If you don't want either, that's the default option. Additional granularity would require to indicate this in the tooltip somehow, when it can just be done by writing details in the OOC information field.

I guess I'll finish with this: TRP3 was ported to Classic because there was a demand for it, but its features are inspired by the evolutions of roleplay on live servers over the years and we are not interested in changing them to emulate what might have been in Vanilla.

**Comment by Corij234** [comment]
> Saying that everyone or even a majority wants to roleplay even if they are set OOC is just wrong.

I never said it was everyone or a majority. Just that often people don't reset their status as often as their mood regarding rp might change... which is just human if you have to change back and forth otherwise.

And how it makes it more confusing or "granulated" to be able to leave an info out, as is possible in every other field in the addon, I just don't get, but hey, guess that is the "evolution". You have to choose one or the other or not use the addon at all if you want to keep your game play more open and just don't fall into either of the two extremes all the time :(
