### ISSUE TITLE
NPC talk detection prefix tooltip states non-EMOTE channels are supported

### ISSUE THREAD

**Issue by Meorawr** [Total-RP/Total-RP-3#490]
The chat frame code for detecting NPC talk only works on the EMOTE channel despite what our tooltip says for the NPC talk detection pattern setting.

https://github.com/Total-RP/Total-RP-3/blob/e8d2561612d22c6f054070b65c38997db39a6d7b/totalRP3/modules/chatframe/chatframe.lua#L606

https://github.com/Total-RP/Total-RP-3/blob/e8d2561612d22c6f054070b65c38997db39a6d7b/totalRP3/tools/Locale.lua#L595

This has been broken for ~4 years as part of what looks like a rewrite of the chat frame code in e6a60c2. Either it was broken unintentionally or the tooltip text wasn't updated to account for the change - either way one of them needs correcting.

**Comment by Ellypse** [comment]
This change was intentional as supporting `SAY` would be difficult for "headless" emotes, such as `/say | The snow glows white on the mountain tonight.`. For `EMOTE` we replace the character name by the first word, so `The` here, which makes it clickable. If we were to do the same for `SAY` it would appear as `[The]: snow glows white`, or worse with possible chat addons installed (Like `[The:60:Group 2]: snow glows white`.

`EMOTE` is the only channel that will not format the messages in such way.
