### ISSUE TITLE
Cannot edit "About" page

### ISSUE THREAD

**Issue by TheGroxEmpire** [Total-RP/Total-RP-3#579]
## Describe the issue
Give us a clear and concise description of what the issue is.
Cannot edit profile "About". It only shows blank canvas.
## Expected behaviour
I should be able to edit the "About" page.
## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [ ] The issue occurs with the [latest Retail version] of the addon.
- [x] The issue occurs with the [latest Classic version] of the addon.
- [x] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Go to "Grahand" profile
2. Go to "About"
3. Click "Edit"

## Additional files

[totalRP3.zip](https://github.com/Total-RP/Total-RP-3/files/6564798/totalRP3.zip)

![image](https://user-images.githubusercontent.com/47816228/120073716-c1f2c280-c0c3-11eb-9532-de5c7644384e.png)

---

**Comment by Solanya** [comment]
It looks like the profile was not properly created but instead copied straight from the directory, which would not work as the structures are not identical.
We are working on a way to have people help you recover your profiles if they have it in their directory but in the meantime, profiles should be recreated normally rather than copying parts of data files.
