### ISSUE TITLE
TRP3 blanks out tooltips when using TipTac Reborn

### ISSUE THREAD

**Issue by ThalliaG** [Total-RP/Total-RP-3#669]
## Describe the issue
The tooltip is completely blank for everything except TRP3 profiles while using TipTac Reborn. Thanks for all that you do and any help would be appreciated!

## Expected behaviour
Prior to this update, TipTac Reborn and TRP3 worked seamlessly together with all tooltips showing, no problem!

## Issue checklist
- [x ] The issue occurs with the [latest version] of the addon.
- [ x] The issue occurs with Total RP 3 as the only enabled addon.
- [x ] The issue occurs only with other addon(s) enabled (please provide a list). TipeTac Reborn

## Steps to reproduce
1. Use TipTac and TRP3 with both enabled.
2. Mouse over a person or ability.
3. You'll see a blank box.
4. Run TipTac Reborn without TRP3 enabled.
5. Mouse over a person or ability.
6. Tooltips work perfectly.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
Testing using both TRP and TipTac Reborn and didn't notice anything unusual 🤔 
If both addons are indeed up-to-date (TRP3 2.4.1, TipTac Reborn 22.11.15, check both **in-game**, not in an addon client), I would need to know if specific options are triggering the issue, or making sure the TipTac module is enabled in Modules status.
Otherwise, you can try `/console scriptErrors 1`, reload and see if any Lua errors appear when the tooltips are blank.

![Untitled](https://user-images.githubusercontent.com/17127080/202313983-8f43579c-25b7-43c9-b27f-b08d55c39754.png)
![Untitled](https://user-images.githubusercontent.com/17127080/202314881-50334d57-c27d-4714-a83a-c1ae29e453ab.png)
![Untitled](https://user-images.githubusercontent.com/17127080/202314942-f8bbcbfe-8cbb-4153-8030-5e14639de226.png)

**Comment by Meorawr** [comment]
Closing as a stale issue that can't be reproduced.
