### ISSUE TITLE
Adding missing icons

### ISSUE THREAD

**Issue by Minaeem** [Total-RP/Total-RP-3#678]
Hello !

I've tried to find some icons for my profils, but some are not in TRP, like the icon of the pet "Blinky" or the icon of the parts of the transmog set  "Sprite Darter"

These icons in game have names like "4080512" and "3071791" maybe it's the reason why you haven't put them, if it's the case, could it be possible to add them with another name ?

Thanks for your time and your super addon ! Have a nice day ! :D

**Comment by Meorawr** [comment]
Unfortunately those icons are part of encrypted content and are only accessible through file IDs. Our current icon mechanism relies on file paths rather than IDs, and there's a few non-trivial issues preventing us from being able to use IDs at present.

It's something we'd like to solve for the future, but it's definitely not a near-term problem.
