### ISSUE TITLE
Only loadable on demand

### ISSUE THREAD

**Issue by Saelsin** [Total-RP/Total-RP-3#794]
## Describe the issue
Im trying to load my TRP 3 data but it WILL not show up. Despite it working perfectly fine yesterday.

## Expected behaviour
For my data to load

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [ x] The issue occurs with Total RP 3 as the only enabled addon.
- [x ] The issue occurs only with other addon(s) enabled (please provide a list).
- Dmb
- Details

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Go to ''

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
totalRP3_Data is intended to show as Loadable on demand, this is not an issue.

Which "data" is missing?

**Comment by Saelsin** [comment]
Total rp 3: Data. It won't load. Only says loadable on demand. Won't load
what profiles I had saved.

**Comment by Solanya** [comment]
Again, Loadable on demand is not an issue, it has nothing to do with whatever problem you're encountering.

Are you talking about your profiles or profiles from other players?

**Comment by Saelsin** [comment]
Well then what can I do to fix it? None of my profiles want to load because
the data file is unresponsive. On any charachter I had a profile is blank.

**Comment by Solanya** [comment]
Alright, so the issue is that your profiles are gone. **Not only is that, again, not related to totalRP3_Data being loadable on demand in any way, it has nothing to do with totalRP3_Data at all**, as that only handles other players' profiles stored in the profile directory.

Now, as for how to solve the issue... Unless you have kept backups of your addon data files (https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables) or of the profiles export strings before they were lost, it's unlikely that there's anything to recover.

Data files are written and read by the game, we don't have any control over that part, and the game may occasionally fail to properly write data upon exit and corrupt the data files, leading to them being reset upon next game launch.

The only advice we can provide going forward is regularly backup your data files, which can be done automatically using a cloud service: https://github.com/Total-RP/Total-RP-3/wiki/How-to-backup-and-synchronize-your-add-ons-settings-using-a-cloud-service
